export const tempData = [
  {
    chatId: 1,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-01T14:01:01',
    isMine: true,
  },
  {
    chatId: 2,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-01T14:01:02',
    isMine: true,
  },
  {
    chatId: 3,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-01T14:01:03',
    isMine: true,
  },
  {
    chatId: 4,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-01T14:02:01',
    isMine: true,
  },
  {
    chatId: 5,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-01T14:02:01',
    isMine: true,
  },
  {
    chatId: 6,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-01T14:02:02',
    isMine: true,
  },
  {
    chatId: 7,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-01T14:03:01',
    isMine: true,
  },
  {
    chatId: 8,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-01T14:03:00',
    isMine: false,
  },
  {
    chatId: 9,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: 'ㅇㅋ',
    chatType: 'USER',
    sentAt: '2023-11-01T14:04:01',
    isMine: false,
  },
  {
    chatId: 10,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-01T14:04:02',
    isMine: false,
  },
  {
    chatId: 11,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-02T14:01:01',
    isMine: true,
  },
  {
    chatId: 12,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-02T14:01:02',
    isMine: true,
  },
  {
    chatId: 13,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-02T14:01:03',
    isMine: true,
  },
  {
    chatId: 14,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-02T14:02:01',
    isMine: true,
  },
  {
    chatId: 15,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-02T14:02:01',
    isMine: true,
  },
  {
    chatId: 16,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-02T14:02:02',
    isMine: true,
  },
  {
    chatId: 17,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-02T14:03:01',
    isMine: true,
  },
  {
    chatId: 18,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-02T14:03:00',
    isMine: false,
  },
  {
    chatId: 19,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: 'ㅇㅋ',
    chatType: 'USER',
    sentAt: '2023-11-02T14:04:01',
    isMine: false,
  },
  {
    chatId: 20,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-02T14:04:02',
    isMine: false,
  },
  {
    chatId: 21,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-03T14:01:01',
    isMine: true,
  },
  {
    chatId: 22,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-03T14:01:02',
    isMine: true,
  },
  {
    chatId: 23,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-03T14:01:03',
    isMine: true,
  },
  {
    chatId: 24,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-03T14:02:01',
    isMine: true,
  },
  {
    chatId: 25,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-03T14:02:01',
    isMine: true,
  },
  {
    chatId: 26,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-03T14:02:02',
    isMine: true,
  },
  {
    chatId: 27,
    senderId: '내 회원 UUID 정보',
    senderNickname: '김이박',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '형, 엄마가 밥먹으래',
    chatType: 'USER',
    sentAt: '2023-11-03T14:03:01',
    isMine: true,
  },
  {
    chatId: 28,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-03T14:03:00',
    isMine: false,
  },
  {
    chatId: 29,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: 'ㅇㅋ',
    chatType: 'USER',
    sentAt: '2023-11-03T14:04:01',
    isMine: false,
  },
  {
    chatId: 30,
    senderId: '다른 회원의 UUID 정보',
    senderNickname: '형',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent:
      '내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?내용이 길어지면?',
    chatType: 'USER',
    sentAt: '2023-11-03T14:04:02',
    isMine: false,
  },
  {
    chatId: 31,
    senderId: 'SYSTEM',
    senderNickname: 'SYSTEM',
    senderProfileUrl: null,
    senderThumbnailUrl: null,
    chatContent: '(형)님이 채팅방을 나갔습니다.',
    chatType: 'SYSTEM',
    sentAt: '2023-11-02T14:04:03',
    isMine: false,
  },
]
