name: CI/CD
on:
  push:
    paths:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

env:
  LONG_CACHE: '--cache-control public,max-age=31536000,immutable'
  SHORT_CACHE: '--cache-control public,max-age=0,no-cache,must-revalidate'
  S3_SYNC_OPTS: '--delete'
  CSP_NONCE: ''

jobs:
  client-CI-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Generate CSP nonce
        id: nonce
        run: |
          NONCE=$(openssl rand -base64 16 | tr '+/' '-_' | tr -d '=')
          echo "CSP_NONCE=$NONCE" >> $GITHUB_ENV
          echo "::add-mask::$NONCE"

      - name: Create .env
        run: |
          echo "ref = $GITHUB_REF"
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            echo "${{ secrets.MAIN_ENV }}" > .env
          else
            echo "${{ secrets.DEV_ENV }}" > .env
          fi

      - name: Build and Export
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload static assets (MAIN)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_MAIN_BUCKET_NAME }}
          aws s3 sync ./out s3://$BUCKET \
              --exclude "index.html" $LONG_CACHE $S3_SYNC_OPTS

      - name: Upload index.html (MAIN)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_MAIN_BUCKET_NAME }}
          aws s3 cp ./out/index.html s3://$BUCKET/index.html $SHORT_CACHE

      - name: Upload static assets (DEV)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_DEV_BUCKET_NAME }}
          aws s3 sync ./out s3://$BUCKET \
              --exclude "index.html" $LONG_CACHE $S3_SYNC_OPTS

      - name: Upload index.html (DEV)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_DEV_BUCKET_NAME }}
          aws s3 cp ./out/index.html s3://$BUCKET/index.html $SHORT_CACHE
