name: CI/CD
on:
  push:
    paths:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  client-CI-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Create Env File for Main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.MAIN_ENV }}" | base64 -d > .env

      - name: Create Env File for Develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo "${{ secrets.DEV_ENV }}" | base64 -d > .env

      - name: Build and Export
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Get Changed Files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v44
      #   with:
      #     files: 'out/**'

      # - name: Deploy to Main S3 and Invalidate CloudFront cache
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: |
      #     aws s3 sync ./out s3://${{ secrets.AWS_S3_CLIENT_MAIN_BUCKET_NAME }} --delete
      #     CHANGED_FILES_PATHS="${{ steps.changed-files.outputs.all_changed_files }}"

      #     if [ ! -z "$CHANGED_FILES_PATHS" ]; then
      #       CLOUD_FRONT_PATHS=$(echo "$CHANGED_FILES_PATHS" | sed -e 's/^out\///' -e 's/^/\//' | tr '\n' ' ')
      #       echo "Invalidating CloudFront cache for the following files: $CLOUD_FRONT_PATHS"
      #       aws cloudfront create-invalidation \
      #         --distribution-id ${{ secrets.AWS_CLOUDFRONT_MAIN_DISTRIBUTION_ID }} \
      #         --paths $CLOUD_FRONT_PATHS
      #     else
      #       echo "No files changed in 'out/' directory, skipping CloudFront invalidation."
      #     fi

      # - name: Deploy to Dev S3 and Invalidate CloudFront cache
      #   if: ${{ github.ref == 'refs/heads/develop' }}
      #   run: |
      #     aws s3 sync ./out s3://${{ secrets.AWS_S3_CLIENT_DEV_BUCKET_NAME }} --delete
      #     CHANGED_FILES_PATHS="${{ steps.changed-files.outputs.all_changed_files }}"

      #     if [ ! -z "$CHANGED_FILES_PATHS" ]; then
      #       CLOUD_FRONT_PATHS=$(echo "$CHANGED_FILES_PATHS" | sed -e 's/^out\///' -e 's/^/\//' | tr '\n' ' ')
      #       echo "Invalidating CloudFront cache for the following files: $CLOUD_FRONT_PATHS"
      #       aws cloudfront create-invalidation \
      #         --distribution-id ${{ secrets.AWS_CLOUDFRONT_DEV_DISTRIBUTION_ID }} \
      #         --paths $CLOUD_FRONT_PATHS
      #     else
      #       echo "No files changed in 'out/' directory, skipping CloudFront invalidation."
      #     fi

      # ============== MAIN 배포 ==============
      - name: Upload static assets (MAIN)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_MAIN_BUCKET_NAME }}
          # index.html 제외, 장기 캐시
          aws s3 sync ./out s3://$BUCKET \
              --exclude "index.html" $LONG_CACHE $S3_SYNC_OPTS

      - name: Upload index.html (MAIN)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_MAIN_BUCKET_NAME }}
          aws s3 cp ./out/index.html s3://$BUCKET/index.html $SHORT_CACHE

      # ============== DEVELOP 배포 ==============
      - name: Upload static assets (DEV)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_DEV_BUCKET_NAME }}
          aws s3 sync ./out s3://$BUCKET \
              --exclude "index.html" $LONG_CACHE $S3_SYNC_OPTS

      - name: Upload index.html (DEV)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          BUCKET=${{ secrets.AWS_S3_CLIENT_DEV_BUCKET_NAME }}
          aws s3 cp ./out/index.html s3://$BUCKET/index.html $SHORT_CACHE